version: '3'
services:
  db:
    image: mongo:latest
    ports:
      - '27017:27017'
    command: '--noauth --bind_ip=0.0.0.0'

  auth:
    build: ./auth-service
    command: nodemon -L src/index.js
    volumes:
      - ./auth-service:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '8080:8080'
    depends_on:
      - db
    links:
      - db
    environment:
      DATABASE_URL: mongodb://db/users
      HOST: '0.0.0.0'
      PORT: '8080'
      SECRET: 'myauthsecret'
